package org.transparent.diamond;

public class DiamondConfigExtension {
    /**
     * Automatically generate a Maven publication that consists of
     * the JAR(s) generated by the <code>java</code> component and a source code JAR.
     * <br/>
     * Mostly intended for usage in Project Transparent's projects.
     */
    public boolean autoMavenPublish = false;
}
